### PR TITLE
switch to logger

### PR DESCRIPTION
**Pull request by daroczig**
Hey @bra-fsn,

Could you please do a quick sanity check on the below?
It should be only switching from `futile.logger` pkg to `logger`.

And if you are still using the pkg, let me know what time works best to deploy this.

### CODE REVIEW

**Comment by bra-fsn** [comment]
Did a quick test, everything seems to be fine. Please give me one day to make some modifications.
Thanks!

**Comment by daroczig** [comment]
@bra-fsn pls let me know when it's good to merge to `master`

**Comment by bra-fsn** [comment]
> @bra-fsn pls let me know when it's good to merge to `master`

Anytime is good

**Comment by daroczig** [comment]
awesome, thanks :bow:

**Pull request merged**
