### PR TITLE
Add auto bid to ad set function

### PR DESCRIPTION
**Pull request by 13bzhang**
Added auto bid to `fbad_create_adset` so Facebook can automatically calculate your bid amount.

### CODE REVIEW

**Comment by 13bzhang** [comment]
Ready to merge!

**Comment by 13bzhang** [comment]
Looks good!

**Comment by daroczig** [comment]
Thanks for this! Can you please simplify the logic and do less copy/paste by checking if `is_autobid` is `TRUE` then `params$is_autobid  <= TRUE`, otherwise set the bid amount of the list?

**Comment by 13bzhang** [comment]
@daroczig I will make the changes.

**Pull request closed without merging**
